version: '3'
services:
  server:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    network_mode: host
    restart: always
    env_file: .env/server.env
    entrypoint: sh ./release.sh
