version: '3'
services:
  server:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    networks:
      - database
    restart: always
    env_file: .env/server.env
    entrypoint: sh ./release.sh

networks:
  database:
    external: true
